import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import SessionWrapper from "./components/SessionWrapper";
import { ShoppingCartProvider } from "./context/ShoppingCartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "3legant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ShoppingCartProvider>
      <SessionWrapper>
        <html lang="en">
          <body className={inter.className}>
            <NavBar />
            {children}
            <Footer />
          </body>
        </html>
      </SessionWrapper>
    </ShoppingCartProvider>
  );
}
